---
- name: Update and Upgrade system
  apt:
    upgrade: full
    autoclean: yes
    autoremove: yes
    update_cache: yes
- name: Permit IP Forwarding
  sysctl:
    name: "{{ item }}"
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
  - net.ipv4.ip_forward
  - net.ipv6.conf.default.forwarding
  - net.ipv6.conf.all.forwarding
- name: Install VPN product
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - openvpn
  - iptables-persistent
- name: Create VPN group
  group:
    name: vpnuser
- name: Create VPN user
  user:
    name: vpnuser
    group: vpnuser
    home: /etc/openvpn
- name: Copy secret key into /etc/openvpn
# TODO: This should really be done with easy-rsa or similar
  copy:
    src: /vagrant/static.key
    dest: /etc/openvpn/static.key
    mode: 0600
    owner: vpnuser
    group: vpnuser
- name: Create config file
  template:
    src: templates/openvpn.j2
    dest: /etc/openvpn/openvpn.conf
    mode: 0600
    owner: vpnuser
    group: vpnuser
  notify:
  - Reconfigure systemd to start OpenVPN
- name: Configure openvpn defaults
  copy:
    content: 'AUTOSTART="all"'
    dest: /etc/default/openvpn
    mode: 0644
    owner: root
    group: root
  notify:
  - Reconfigure systemd to start OpenVPN
#- name: Configure IPTables
#  template:
#    src: "templates/iptables/{{ item.name }}.j2"
#    dest: "/etc/iptables/{{ item.name }}"
#    mode: 0644
#    owner: root
#    group: root
#    validate: iptables-restore -t %s
#  with_items:
#  - name: rules.v4
#    check: iptables-restore
#  - name: rules.v6
#    check: ip6tables-restore
#  notify:
#  - Reload IPTables
