---
- name: Update and Upgrade system
  apt:
    upgrade: full
    autoclean: yes
    autoremove: yes
    update_cache: yes
- name: Permit IP Forwarding
  sysctl:
    name: "{{ item }}"
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
  - net.ipv4.ip_forward
  - net.ipv6.conf.default.forwarding
  - net.ipv6.conf.all.forwarding
- name: Install VPN product
  apt:
    name: openvpn
- name: Create VPN group
  group:
    name: vpnuser
- name: Create VPN user
  user:
    name: vpnuser
    group: vpnuser
    home: /etc/openvpn
- name: Copy secret key into /etc/openvpn
  copy:
    src: /vagrant/static.key
    dest: /etc/openvpn/static.key
    mode: 0600
    owner: vpnuser
    group: vpnuser
- name: Create config file
  template:
    src: templates/openvpn.j2
    dest: /etc/openvpn/openvpn.conf
    mode: 0600
    owner: vpnuser
    group: vpnuser
